<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Temoprary Home Page</title>
    </head>
    <body>
    <h1>schiess8.GitHub.io<h1>
      <p>THis is a temorary home page served from GitHub respository.</p>
    </body>
</html>